import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import StyledComponentsRegistry from "./lib/registry";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

import { Header, Footer } from "./common/components";
import Script from "next/script";
import Head from "next/head";
import { montserrat } from "./fonts";

export const metadata: Metadata = {
  title: "Al-Hodhod",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script
        id="adsense-script"
        async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4511775489420895"
        strategy="lazyOnload"
        crossOrigin="anonymous"
      ></Script>
      <body
        className={montserrat.variable}
      >
        <StyledComponentsRegistry>
          <Header />
          {children}
          <SpeedInsights />
          <Analytics />
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
